[package]
name = "pigeonvc2"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pigeonvc2-server"
path = "src/server-cli/main.rs"

[dependencies]
anyhow = "1.0.100"
dashmap = "6.1.0"
tokio = { version = "1.48.0", features = ["full"] }
